trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '6d15ccab-83de-418a-91ff-fec2af415ebd'

  # Web app name
  webAppName: 'react-app-automate'

  # Environment name
  environmentName: 'react-app-automate'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'  # Updated to the latest Node.js version used in your local environment
      displayName: 'Install Node.js'

    - script: npm ci  # Use npm ci instead of npm install for faster, reliable builds
      displayName: 'Install dependencies'

    - script: npm run build
      displayName: 'Build the React app'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile:  $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Publish Artifact'
      artifact: drop