name: Build and Push Docker Image to Amazon ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the main branch
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Amazon ECR using AWS credentials stored in secrets
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Build, tag, and push the Docker image to ECR
      - name: Build, tag, and push image to ECR
        run: |
          docker build -t react-automate .
          docker tag react-automate:latest 299030377158.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/react-automate:latest
          docker push 299030377158.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/react-automate:latest

      # Decode the SSH private key from the base64-encoded secret
      - name: Decode SSH key
        run: echo "${{ secrets.EC2_SSH_KEY_BASE64 }}" | base64 --decode > kafka1.pem

      # Check if the SSH key was successfully created
      - name: Check if SSH key exists
        run: ls -l kafka1.pem

      # Set proper permissions for the SSH key
      - name: Set correct permissions for SSH key
        run: chmod 600 kafka1.pem

      # Debug SSH key content (optional)
      - name: Debug SSH key content
        run: head -n 10 kafka1.pem

      # Deploy to EC2 via SSH and run deployment commands
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: kafka1.pem
          key_type: pem
          port: 22
          script: |
            sudo systemctl stop nginx
            docker stop react-automate || true
            docker rm react-automate || true
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 299030377158.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            docker pull 299030377158.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/react-automate:latest
            docker run -d -p 80:3000 --name react-automate 299030377158.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/react-automate:latest
