name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: '18'  # Specify your project's Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      - name: Debug - Verify .ssh directory
        run: ls -la ~/.ssh

      - name: Decode SSH key
        run: echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
        shell: bash

      - name: Set correct permissions
        run: chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: ~/.ssh/id_rsa  # Use the decoded SSH key
          script: |
            cd /home/ec2-user
            git pull origin main
            npm install
            npm run build
            sudo systemctl restart nginx