name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Save SSH private key
        run: echo "${{ secrets.EC2_SSH_KEY }}" > ~/Downloads/kafka1.pem
      
      - name: Set SSH key permissions
        run: chmod 600 ~/Downloads/kafka1.pem
      
      - name: Zip the dist directory
        run: zip -r dist.zip dist/
      
      - name: Transfer file via SCP
        run: |
          scp -o StrictHostKeyChecking=no -i ~/Downloads/kafka1.pem dist.zip ec2-user@54.80.226.154:/home/ec2-user
      
      - name: Deploy on remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/Downloads/kafka1.pem ec2-user@54.80.226.154 "
            rm -vrf /home/ec2-user/* && \
            mv /home/ec2-user/dist.zip /home/ec2-user/ && \
            cd /home/ec2-user && \
            unzip -o dist.zip && \
            mv dist/* . && \
            rm -rf dist dist.zip"
      
      - name: Cleanup
        run: rm dist.zip
