name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: '18'  # Specify your project's Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build


      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user
            git pull origin main
            npm install
            npm run build
            sudo systemctl restart nginx
env:
  ACTIONS_STEP_DEBUG: true