name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: List contents of workspace
        run: |
          echo "Listing contents of the workspace directory:"
          ls -la $GITHUB_WORKSPACE

      - name: Check for dist directory
        run: |
          echo "Checking if dist directory exists:"
          if [ -d "$GITHUB_WORKSPACE/dist" ]; then
            echo "dist directory found."
            ls -la $GITHUB_WORKSPACE/dist
          else
            echo "Error: dist directory does not exist."
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Save SSH private key
        run: echo "${{ secrets.EC2_SSH_KEY }}" > $GITHUB_WORKSPACE/kafka1.pem

      - name: Set SSH key permissions
        run: chmod 600 $GITHUB_WORKSPACE/kafka1.pem

      - name: Zip the build directory
        run: |
          echo "Preparing to zip the build directory..."
          if [ -d "$GITHUB_WORKSPACE/dist" ]; then
            zip -r dist.zip dist/
          else
            echo "Error: dist directory does not exist."
            exit 1
          fi

      - name: Transfer file via SCP
        run: |
          echo "Transferring zip file to remote server..."
          scp -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/kafka1.pem dist.zip ec2-user@54.80.226.154:/home/ec2-user

      - name: Deploy on remote server
        run: |
          echo "Deploying to remote server..."
          ssh -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/kafka1.pem ec2-user@54.80.226.154 "
            rm -vrf /home/ec2-user/* && \
            mv /home/ec2-user/dist.zip /home/ec2-user/ && \
            cd /home/ec2-user && \
            unzip -o dist.zip && \
            mv dist/* . && \
            rm -rf dist dist.zip"

      - name: Cleanup
        run: rm dist.zip
